# -*- coding: utf-8 -*-
"""Lv0_0000_프로그래머스_짝수홀수개수_구현_재호.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PUk_e8Stz0u4SkpNoDgshiYOSwhlhgo9
"""

def solution(num_list):
    even_list = []
    odd_list = []
    
    for i in num_list:
        if i % 2 == 0:
            even_list.append(i)
        else:
            odd_list.append(i)
        
    return [len(even_list), len(odd_list)]