# -*- coding: utf-8 -*-
"""Lv0_0000_프로그래머스_각도기_구현_재호.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PUk_e8Stz0u4SkpNoDgshiYOSwhlhgo9
"""

def solution(angle):
    if 0 < angle < 90:
        return 1
    elif angle == 90:
        return 2
    elif 90 < angle < 180:
        return 3
    else:
        return 4