# -*- coding: utf-8 -*-
"""Lv0_0000_프로그래머스_양꼬치_구현_재호.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PUk_e8Stz0u4SkpNoDgshiYOSwhlhgo9
"""

def solution(n, k):
    result = 12000*n + 2000*k
    if n >= 10:
        result -= 2000*(n // 10)
    return result