# -*- coding: utf-8 -*-
"""Lv0_0000_프로그래머스_아이스아메리카노_구현_재호.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PUk_e8Stz0u4SkpNoDgshiYOSwhlhgo9
"""

def solution(money):
    cup = money // 5500
    change = money % 5500
        
    return [cup, change]