# -*- coding: utf-8 -*-
"""Lv0_0000_프로그래머스_배열원소의길이_구현_재호.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PUk_e8Stz0u4SkpNoDgshiYOSwhlhgo9
"""

def solution(strlist):
    answer = []
    for i in strlist:
        answer.append(len(i))
    return answer