# -*- coding: utf-8 -*-
"""Lv0_0000_프로그래머스_피자나눠먹기_구현_재호.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PUk_e8Stz0u4SkpNoDgshiYOSwhlhgo9
"""

def solution(n):
    return (n - 1) // 7 + 1