# -*- coding: utf-8 -*-
"""Lv0_0000_프로그래머스_머쓱이보다키큰사람_구현_재호.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PUk_e8Stz0u4SkpNoDgshiYOSwhlhgo9
"""

def solution(array, height):
    num = 0

    for i in array:
        if i > height:
            num += 1

    return num