# -*- coding: utf-8 -*-
"""Lv0_0000_프로그래머스_배열 두 배 만들기_구현_재호.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PUk_e8Stz0u4SkpNoDgshiYOSwhlhgo9
"""

def solution(numbers):
    result = []
    for num in numbers:
        result.append(num * 2)
    return result