# -*- coding: utf-8 -*-
"""Lv0_0000_프로그래머스_중앙값구하기_구현_재호.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PUk_e8Stz0u4SkpNoDgshiYOSwhlhgo9
"""

def solution(array):
    array.sort()
    answer = (len(array) // 2)
    return array[answer]