# -*- coding: utf-8 -*-
"""Lv0_0000_프로그래머스_삼각형의완성조건(1)_구현_재호.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PUk_e8Stz0u4SkpNoDgshiYOSwhlhgo9
"""

def solution(sides):
    sides.sort()
    if sides[-1] < sides[0] + sides[1]:
        return 1
    else:
        return 2