# -*- coding: utf-8 -*-
"""Lv0_0000_프로그래머스_순서쌍의 개수_구현_재호.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PUk_e8Stz0u4SkpNoDgshiYOSwhlhgo9
"""

def solution(n):
    num_1 = []
    num_2 = []
    for x in range(1, n+1):
        if n % x == 0:
            num_1.append(x)
    for i in num_1:
        for j in num_1:
            if i * j == n:
                num_2.append((i, j))
    return len(num_2)