# -*- coding: utf-8 -*-
"""Lv0_0000_프로그래머스_최댓값만들기(1)_구현_재호.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PUk_e8Stz0u4SkpNoDgshiYOSwhlhgo9
"""

def solution(numbers):
    return sorted(numbers)[-1] * sorted(numbers)[-2]