# -*- coding: utf-8 -*-
"""Lv0_0000_프로그래머스_개미군단_그리디_재호.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PUk_e8Stz0u4SkpNoDgshiYOSwhlhgo9
"""

def solution(hp):
    장군개미수 = hp // 5
    hp = hp - 장군개미수 * 5
    
    병정개미수 = hp // 3
    hp = hp - 병정개미수 * 3
    
    일개미수 = hp // 1
    hp = hp - 일개미수 * 3
    
    return 장군개미수 + 병정개미수 + 일개미수