# -*- coding: utf-8 -*-
"""Lv0_0000_프로그래머스_주사위의개수_구현_재호.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PUk_e8Stz0u4SkpNoDgshiYOSwhlhgo9
"""

def solution(box, n):
    return (box[0] // n) * (box[1] // n) * (box[2] // n)